### ISSUE TITLE
EdgyBot not being verified 

### ISSUE THREAD

**Issue by The30G** [GSRHackZ/EdgyBot_Edgenuity_Bot#100]
I don’t know if this is a bot problem or a user issue but it’s telling me the bot is not verified and I checked and GSRHackz said the order would be completed in less then a hour n ya alr took my money
![image](https://user-images.githubusercontent.com/128866696/227660822-1406ca81-af06-4d50-a440-822e02212ea8.jpg)

**Comment by GSRHackZ** [comment]
Servers have gone down, Please wait until 6:30 am tomorrow. You account will be verified by then. 🙏

**Comment by The30G** [comment]
Ok thank you and when I was paying should I have put my edgenuity info for the username and password for edgebot?

**Comment by GSRHackZ** [comment]
No u could make ur own new username and password

I have verified ur account as of now, please login and lmk 🙏
