### ISSUE TITLE
NEED HELP ASAP

### ISSUE THREAD

**Issue by CamronBray23** [GSRHackZ/EdgyBot_Edgenuity_Bot#103]
Idk if my password isn’t working or if I need to reset it. If I have to reset it I can pay.

**Comment by GSRHackZ** [comment]
No need, wait until tomorrow after 6:30 am and try logging in. if still having issues, contact 9295845325.

**Comment by CamronBray23** [comment]
Could it be because I don’t have the newest version. I thought i did but it says removed
