### ISSUE TITLE
"Online Content" is in the  ungraded afk mode which it shouldn't be.

### ISSUE THREAD

**Issue by GTASHAWDOW1211** [GSRHackZ/EdgyBot_Edgenuity_Bot#105]
For me online content assignments are graded and the bot tends to get 0s on them so may you please remove online content from the ungraded afk mode.

**Comment by GTASHAWDOW1211** [comment]
Does this for "Apply Your Knowledge" as well.

**Comment by GSRHackZ** [comment]
Ok will do so today 🙏
