### ISSUE TITLE
Edgybot problem

### ISSUE THREAD

**Issue by Sanchlui75** [GSRHackZ/EdgyBot_Edgenuity_Bot#107]
![image](https://user-images.githubusercontent.com/128923712/227731259-b92ad21e-0fea-431b-b00a-dc39bf4b7f02.jpg)

Says this for every class, and every assignment on the course map, is edgybot not working correctly rn or what?

**Comment by GSRHackZ** [comment]
Please read instructions....

Instructions and Tool description clearly state that assignments can't be done by EdgyBot 🤦‍♂️
