### ISSUE TITLE
need help with verifying

### ISSUE THREAD

**Issue by h-town505** [GSRHackZ/EdgyBot_Edgenuity_Bot#109]
i payed for edge bot and got the verify but its not working when i login i says waiting for verification did i get scamed

**Comment by GSRHackZ** [comment]
Contact 9295845325, and no you didn't get scammed, what sort of dumbass question is that 🤦‍♂️

**Comment by h-town505** [comment]
> Contact 9295845325, and no you didn't get scammed, what sort of dumbass question is that 🤦‍♂️

i already payed tho
