### ISSUE TITLE
Please Help

### ISSUE THREAD

**Issue by mmcguffee** [GSRHackZ/EdgyBot_Edgenuity_Bot#113]
Edgybot pulls up I chose my class & then nothing. It won't anything at all it just sits there. Can you help me, please?  I am running 3.291. It won't pull up Brainly or anything at all it just sits there.

**Comment by GSRHackZ** [comment]
> Edgybot pulls up I chose my class & then nothing. It won't anything at all it just sits there. Can you help me, please?  I am running 3.291. It won't pull up Brainly or anything at all it just sits there. 

Can you send pictures of the issue?

Actually contact 9295845325

**Comment by mmcguffee** [comment]
It's working now Thank You so much!! I shut down & everything is back up
and running. I'm sorry for bothering you. Thank You for all you do

**Comment by GSRHackZ** [comment]
I'm glad it's fixed 👌
