### ISSUE TITLE
I had Bought Edgeunity bot before but it has been uninstalled in my computer i had bought it before the Username and password to get the bot I payed Gsr 50 dollars for three classes I would like to be verifed again

### ISSUE THREAD

**Issue by TravisKun** [GSRHackZ/EdgyBot_Edgenuity_Bot#115]
I need it to be re verifed I dont have a username and password please let me know thank you

**Comment by mmcguffee** [comment]
OH Ok
username- mmcguffee
pw- Iluvdon_04

**Comment by mmcguffee** [comment]
OH I'm so sorry. I purchased it again after this email I think lol. My
apologies. I think I sent that one a long time ago & it was resolved. Thank
You so much
