### ISSUE TITLE
assignments

### ISSUE THREAD

**Issue by ZaydenFox** [GSRHackZ/EdgyBot_Edgenuity_Bot#116]
is edgy bot ever going to be able to do assignments? the bot just pauses every time it gets to an assignment and won't do anything else. Also annoying a little how we pay and it doesn't do all the work

**Comment by GSRHackZ** [comment]
It clearly states before you even buy it... if you even read the instructions that it doesn't do assignments... so kinda sounds like it's ur fault 🤷‍♂️

**Comment by GSRHackZ** [comment]
> Also annoying a little how we pay and it doesn't do all the work

Like are you expecting a magical solution to all your problems? We don't have every single activity type to test and develop the bot on neither do we have the time to do so. 

We clearly state what the bot can and can't do, you read this before you payed. You payed and agreed to our terms of service along with the disclaimer.

Having an issue with what was clearly stated multiple times in the description, instructions wiki, faq, and thé EdgePlus website?

Shouldn't have bought it 🤷‍♂️
