### ISSUE TITLE
I pressed the wrong classes

### ISSUE THREAD

**Issue by 999LLJW** [GSRHackZ/EdgyBot_Edgenuity_Bot#119]
I need to switch the classes but it says I have to pay?

**Comment by 999LLJW** [comment]
![Screenshot (11)](https://user-images.githubusercontent.com/44493415/228294865-1031955a-c297-45bc-add9-75cd63ae6811.png)

**Comment by GSRHackZ** [comment]
We can't give you new classes for free. This is user error 🤷‍♂️
