### ISSUE TITLE
doesn't let me go afk any more

### ISSUE THREAD

**Issue by jesusAceved** [GSRHackZ/EdgyBot_Edgenuity_Bot#120]
It gives me the answer but it doesn't choose it I have to do it manually

**Comment by Ar1zzen** [comment]
mine doesn't even do that for me anymore it just says stop and activate there is no more auto answer for me no more

**Comment by GSRHackZ** [comment]
> mine doesn't even do that for me anymore it just says stop and activate there is no more auto answer for me no more 

Do you mean no auto search and display of answers?

**Comment by ITAC85v2** [comment]
> mine doesn't even do that for me anymore it just says stop and activate there is no more auto answer for me no more

Please provide more info. Do you mean that no answers are displayed, or do you mean that it won't automatically pick the correct answer choice?

**Comment by GSRHackZ** [comment]
I think this issue was about the EdgyAFK mode being patched, so Imma close because that has been resolved.

**Comment by GSRHackZ** [comment]
Never mind the close of the issue, didn't read it carefully.

**Comment by jesusAceved** [comment]
when will I be able to AFK again

**Comment by GSRHackZ** [comment]
Semi auto answer has been added in v3.35 and full auto answer for tests and quizzes will be added by the end of the week. Issues such as thebot not searching up answers have also been fixed.
