### ISSUE TITLE
ok this isnt much of an issue 

### ISSUE THREAD

**Issue by potato09lol** [GSRHackZ/EdgyBot_Edgenuity_Bot#122]
it was wondering if you could make it more extensible like nullify a iready hack which is highly exesible for chrome books and other things and it works good most of the time unless somthing updates 4

**Comment by GSRHackZ** [comment]
We can not turn this into a bookmarklet due to it relying on certain tampermonkey functions. Thanks for letting us know either way, we might look into making a version that could potentially work as a bookmarklet 🙏
