### ISSUE TITLE
I paid for the bot for a friend long ago but never used it. I have dms

### ISSUE THREAD

**Issue by johnpeter6666** [GSRHackZ/EdgyBot_Edgenuity_Bot#123]
I just need the bot for my hardware to be activated. Here are DMs from me and GSRHackZ long ago...
![dsdsads grz](https://user-images.githubusercontent.com/51056103/228378751-4556f1ff-ea2c-4801-86cd-c89f9abbd4e8.PNG)

**Comment by johnpeter6666** [comment]
Also there wasnt no login info for this acount, so what do I do? or whats the next move.

**Comment by GSRHackZ** [comment]
Contact 9295845325
