### ISSUE TITLE
quiz 

### ISSUE THREAD

**Issue by oliviaetooley** [GSRHackZ/EdgyBot_Edgenuity_Bot#124]
unless im just doing something wrong , but edgebot isn’t working on my quizzes.. as soon as i get to it , it won’t proceed it just shows this page.  i refreshed , and tried to do the inspect method, but still won’t proceed.  
![image](https://user-images.githubusercontent.com/128737081/228414054-962c9c6d-b0e8-4501-bd6f-2d94964e9a9d.jpg)

**Comment by GSRHackZ** [comment]
That just means u didn't do the activities before the quiz. This isn't by us, this is because of Edgenuity. All activities before that quiz have to be done for it to display the green button so u can start the quiz.

**Comment by oliviaetooley** [comment]
ohhhh okay my bad just realized that!  thanks :)
