### ISSUE TITLE
no answers

### ISSUE THREAD

**Issue by Ar1zzen** [GSRHackZ/EdgyBot_Edgenuity_Bot#125]
I've been using this for about 2 weeks and it updated like 4 times but the original one I got when my friend showed me it. it was auto-answering and doing what it was supposed to do but ever scents that first update it hasn't answered 
![problem](https://user-images.githubusercontent.com/128778505/228425495-01aec619-c49a-44d8-bcaa-1e4f7b7153e4.png)

**Comment by GSRHackZ** [comment]
Auto answer is coming, check the other issue before making one.
