### ISSUE TITLE
I put it to quiz and its just stuck in a loop 

### ISSUE THREAD

**Issue by Charley702** [GSRHackZ/EdgyBot_Edgenuity_Bot#127]
i cant do anything except disable the bot ive tried doing a new tab it just automatically goes to the class and puts me in the loop video included 

https://user-images.githubusercontent.com/115515498/228632647-d63174cb-ef08-4a39-8125-3c19bc1b9662.mov

**Comment by ITAC85v2** [comment]
Fixed, now it has the old code before the activity skipper (aka legacy EdgyAFK) was reintroduced.

**Comment by GSRHackZ** [comment]
Edgenuity patched EdgyAFK activity skipper again, so we have reverted back to older version before it was reintroduced to code. Let us know if it has been fixed

**Comment by GSRHackZ** [comment]
Recieved confirmation that new version works from other users. This issue will now be closed.

**Comment by Ar1zzen** [comment]
Please stop sending me emails of other people's problems I figured out I
don't have enough to renew my courses

**Comment by GSRHackZ** [comment]
What?

**Comment by Charley702** [comment]
> Fixed, now it has the old code before the activity skipper (aka legacy EdgyAFK) was reintroduced. Please update to the latest version and lmk if it works.

works thanks👍
