### ISSUE TITLE
my payments on venmo aren't sending

### ISSUE THREAD

**Issue by ItsNotMika** [GSRHackZ/EdgyBot_Edgenuity_Bot#134]
When I was attempting to send in my payment on Venmo but it keeps on being declined. My card does work and I've tried to refresh and find other ways but I keep receiving the same issue.

**Comment by GSRHackZ** [comment]
This isn't an issue to put on GitHub, if you can't send payment then that's that. This is for bug reports or genuine issues on our end. This is none of those 👎
