### ISSUE TITLE
Auto sub

### ISSUE THREAD

**Issue by sho2321** [GSRHackZ/EdgyBot_Edgenuity_Bot#138]
bro it auto submitted a DBQ with an ai response that said some bullshit and now im fucked

**Comment by ITAC85v2** [comment]
The AI we use to make answers in writing assignments sucks at writing essays, so we're going to use ChatGPT. It should be released sometime soon.

**Comment by sho2321** [comment]
> The AI we use to make answers in writing assignments sucks at writing essays, so we're going to use ChatGPT. It should be released sometime soon.

is there any way I can disable it?

**Comment by ITAC85v2** [comment]
> is there any way I can disable it?

Simply just disable EdgyBot in tampermonkey before you open a writing assignment.
