### ISSUE TITLE
not working anymore

### ISSUE THREAD

**Issue by astralghost69** [GSRHackZ/EdgyBot_Edgenuity_Bot#140]
it worked just fine with my 3 classes, that i payed $50 for $10 per class, when i first used it but now it will not do anything properly. what happened?

**Comment by GSRHackZ** [comment]
> it worked just fine with my 3 classes, that i payed $50 for $10 per class, when i first used it but now it will not do anything properly. what happened?

What exactly is it doing wrong? This isn't helping us help u 🤦‍♂️

**Comment by astralghost69** [comment]
ive explained several times

**Comment by GSRHackZ** [comment]
contact 9295845325
