### ISSUE TITLE
New update caused an unfortunate time issue

### ISSUE THREAD

**Issue by WillyDees** [GSRHackZ/EdgyBot_Edgenuity_Bot#141]
Just since this new update released, it now takes the bot longer to find the answers for multiple choice questions making it not worth the wait and might as well go back to looking them up myself so I can speed run the practice and quizzes.

**Comment by GSRHackZ** [comment]
This is in prep for auto answer. The long wait makes sure the bot gets correct answers. Wait till the end of this week, you will see why this long search time is a must.
