### ISSUE TITLE
problem with my purchased classes

### ISSUE THREAD

**Issue by MattyB0524** [GSRHackZ/EdgyBot_Edgenuity_Bot#143]
I bought 14 classes prior to me actually having all 14, so i could not select all 14 only 6, i was wondering if there was anyway to resolve this because when i got my new classes I could not use the bot no more.

**Comment by GSRHackZ** [comment]
> I bought 14 classes prior to me actually having all 14, so i could not select all 14 only 6, i was wondering if there was anyway to resolve this because when i got my new classes I could not use the bot no more.

Yes, contact 9295845325
