### ISSUE TITLE
Instruction, Warmup videos are looping.

### ISSUE THREAD

**Issue by minriyu** [GSRHackZ/EdgyBot_Edgenuity_Bot#146]
Video would play then repeat itself again

**Comment by GSRHackZ** [comment]
Must stay on the same tab while EdgyBot does it's thing. This could possibly be a new Edgenuity update

We will look into this 🙏

**Comment by GSRHackZ** [comment]
Yep it's an Edgenuity Update.

An auto advance fix has been made and will be released this afternoon in v3.36

( will close this issue upon release )

Thanks for reporting 🙏

**Comment by GSRHackZ** [comment]
Nevermind this was an issue on Edgenuity's end. 

![image](https://user-images.githubusercontent.com/79179978/230242270-7aa1367b-0f7d-47d8-b56e-0e686482f038.jpeg)
