### ISSUE TITLE
more classes

### ISSUE THREAD

**Issue by tigerunreal** [GSRHackZ/EdgyBot_Edgenuity_Bot#148]
how do i even get more classes? i got like 5 in total but it only claimed like 3 of them and now that i have the other 2 its telling me its not part of my plan? like im not gonna pay a 20 dollar base price again just bc it didnt activate

**Comment by GSRHackZ** [comment]
All you had to do was ask... stop complaining 🤦‍♂️ 

Contact 9295845325
