### ISSUE TITLE
Edgy RAY

### ISSUE THREAD

**Issue by Rmarsh85** [GSRHackZ/EdgyBot_Edgenuity_Bot#153]
My auto clicker for edgy bot not working but long story short nothing is working its not automatically answering test quizes or nothing i have to do everything.And what i seen in the video is what im not getting.

**Comment by GSRHackZ** [comment]
Contact 9295845325

**Comment by Rmarsh85** [comment]
hey my edgy bot want let me log in i reset my pc and it want let me log in
