### ISSUE TITLE
It will answer one question then it wont search for anymore it will just turn off

### ISSUE THREAD

**Issue by ZaydenFox** [GSRHackZ/EdgyBot_Edgenuity_Bot#157]
Im doing a unit test and it will search for the question then ill go to the next question and it will just stop working

**Comment by GSRHackZ** [comment]
Did this issue happen in the previous version, v3.35 or is it a new issue in v3.36?

**Comment by ZaydenFox** [comment]
The new one

**Comment by ZaydenFox** [comment]
should i try and Reinstall or is there a way I can go back to old version?

**Comment by GSRHackZ** [comment]
I have released v3.37, lmk if that fixes the issue 🙏

**Comment by ZaydenFox** [comment]
it did fix it

**Comment by ZaydenFox** [comment]
Just a question, why cant the bot search the internet for the assignment questions like it can quizzes and everything?

**Comment by GSRHackZ** [comment]
Too many different variations in questions for assignments and the bot wouldn't be able to understand each question and search it correctly, at least not at the moment.

Also I'm glad that update fixed it 🙏
