### ISSUE TITLE
Pick a class for EdgyBot to work on... 🤖

### ISSUE THREAD

**Issue by sufficerice** [GSRHackZ/EdgyBot_Edgenuity_Bot#163]
Recently got two new classes added to my Edgenuity and bought the service for two classes, Chem. and Art but my options arent popping up to start the bot for those classes. Any help? (Purchase was verified according to EdgePlus+ site)

![Screenshot (3)](https://user-images.githubusercontent.com/130512661/231305614-127722fa-38c9-41c0-87f1-16121e94da3e.png)
![Screenshot (4)](https://user-images.githubusercontent.com/130512661/231305659-82844365-81a9-4ad5-885b-b50e45768fc6.png)

**Comment by GSRHackZ** [comment]
Contact 9295845325
