### ISSUE TITLE
Sorry if I'm putting this in the wrong place but I mean no stress by this but when is full automation available?, maybe I can downgrade to the older version that had it? Dm me on insta: ryawya

### ISSUE THREAD

**Issue by ryawya** [GSRHackZ/EdgyBot_Edgenuity_Bot#164]

**Comment by GSRHackZ** [comment]
Will be added again this week. Thanks for the issue. 

(Was removed so we can make it better in a slow and steady manner, that way we fix bugs per release making auto answer as perfect as can be)
