### ISSUE TITLE
Auto answer and a next button

### ISSUE THREAD

**Issue by 999LLJW** [GSRHackZ/EdgyBot_Edgenuity_Bot#165]
look man, I'm not sure what you did to the bot but the old versions were much better than this we used to have auto submit and auto answer. why won't you just combine everything in one and see how it goes because I just paid $50 do sit here and do the work myself and it's messed up.

**Comment by 999LLJW** [comment]
And when I finish some assignments I have to back out of the session and click the class again so is there a way you can get the bot to move on to the next lesson?

**Comment by 999LLJW** [comment]
![Screenshot (13)](https://user-images.githubusercontent.com/44493415/231529692-5a57c71a-f148-4106-b06f-48169b0bcdcd.png)

**Comment by 999LLJW** [comment]
If you see in the image theres no next button

**Comment by ZaydenFox** [comment]
Agreed that I have to go back to the home page and start it up again. Also, have to completely get rid of the bot off my computer when an assignment comes up because it just freezes. Would also like old version back

**Comment by GSRHackZ** [comment]
Fixed this issue, it will now leave the activity when done and open the next activity. Thanks for the feedback 🙏

(These changes will take place in the next version, v3.39)
