### ISSUE TITLE
Auto Answer

### ISSUE THREAD

**Issue by sho2321** [GSRHackZ/EdgyBot_Edgenuity_Bot#166]
I don't know if this is a issue or not but I'm new to github and I have no idea where else to put it. I've noticied GSRHackZ and other people have an auto answer for quizzes but my EdgyBot doesn't have this feature from my knowledge and I was wondering if theres anything I can do to enable it or get it to work. (I've turned off all ad blockers and switched to bing while using it if this means anything)

**Comment by GSRHackZ** [comment]
Auto answer was removed so we ca work on it and release a better version. This better version will be added back this week.
