### ISSUE TITLE
Bot

### ISSUE THREAD

**Issue by juggindee** [GSRHackZ/EdgyBot_Edgenuity_Bot#167]
Hello so I can't choose what work I want it to do and it won't let me do auto answer. Any solution to fix it?

**Comment by GSRHackZ** [comment]
No, this is intended. Activity selection and skipping has been patched by Edgenuity. Auto answer releases this week for tests and quizzes.

**Comment by juggindee** [comment]
Oh ok so I have too let it finish all the way through too select something
else?

**Comment by GSRHackZ** [comment]
as in finish the activity? yes

**Comment by juggindee** [comment]
Like finish all the activities I wanted it to finish too get it too work on
something else
