### ISSUE TITLE
Making me login over and over

### ISSUE THREAD

**Issue by andrewfiala7** [GSRHackZ/EdgyBot_Edgenuity_Bot#168]
I can’t get into my edgybot it’s keeps telling me to login and then when I login it ask to login again help
![image](https://user-images.githubusercontent.com/130719429/231920732-cc028cc5-0ded-4a29-b1ea-7c7ac8fee861.jpg)

**Comment by GSRHackZ** [comment]
It means your information is incorrect. Contact 9295845325
