### ISSUE TITLE
Purchased three new classes but did not let me activate.

### ISSUE THREAD

**Issue by MattyB0524** [GSRHackZ/EdgyBot_Edgenuity_Bot#172]
![unknown_2023 04 16-13 40_1](https://user-images.githubusercontent.com/129830586/232341141-93022521-443b-4959-9b2a-c7a3d78e0252.gif) Shows my last six only

**Comment by MattyB0524** [comment]
I have proof of purchase from today as well

**Comment by GSRHackZ** [comment]
Contact 9295845325
