### ISSUE TITLE
AFK edgy bot

### ISSUE THREAD

**Issue by joeseff2** [GSRHackZ/EdgyBot_Edgenuity_Bot#175]
When edge bot first started there was a menu where you could choose which assignments to work on I was wondering if there is still a way to do that

**Comment by Jugg34** [comment]
Yea it only pops up if your assignments are locked

**Comment by Wesleyy05** [comment]
this was the best feature like where did it go

**Comment by GSRHackZ** [comment]
This was patched. It's not like we wanted to remove it 🤦‍♂️
