### ISSUE TITLE
remove all edgebot activities from screen once “stopedgebot” has been clicked

### ISSUE THREAD

**Issue by Ashtozovi** [GSRHackZ/EdgyBot_Edgenuity_Bot#176]
i made a request to change the font to black and you guys have done a fckin good ass job💪🏽. but how good would it be if the whole edgybot can be off the screen once you click “stop edgebot”.  ive clicked it but it still shows the edgebot answers. so i think if the whole edgebot program could be erased from the screen once stop edgebot has been clicked would be a game changer too😅💯💪🏽!!!!!

**Comment by GSRHackZ** [comment]
I like your recommendation. If it's not added in todays later update, it will be very soon 🙏

**Comment by Mrbitz17** [comment]
how do I turn it off? I don't use it anymore.
