### ISSUE TITLE
Add back assignments skips

### ISSUE THREAD

**Issue by boolinb** [GSRHackZ/EdgyBot_Edgenuity_Bot#179]
There use to be this thing for assignments where you wouldn't have to wait for the reader to read it all and then you could answer. This doesn't work anymore and I was wondering if you could add it back please? It made doing the assignments 10 times easier and quicker. Pretty much you could just answer it and click through without waiting for anything.

**Comment by GSRHackZ** [comment]
Being added. Was removed for fixing 🙏
