### ISSUE TITLE
Quiz and Test issue 

### ISSUE THREAD

**Issue by v5mp** [GSRHackZ/EdgyBot_Edgenuity_Bot#181]
I do not know if it is just me or something but all of the question that are on my quizzes and test i have taken like 4 of them or more already and i have to manually search them on my own, Again im not sure if that is just me, but if there is any issues let me know

**Comment by lawrabe** [comment]
you're not the only one. before the update edgybot was able to do my quizzies for me and it would display all the answers while i was taking a quiz but after i updated i have to manually search every answer :/ 👎

**Comment by GSRHackZ** [comment]
All issues will be fixed in todays later update 👌
