### ISSUE TITLE
wont select

### ISSUE THREAD

**Issue by studiossn** [GSRHackZ/EdgyBot_Edgenuity_Bot#185]
wont let me pick my class 

only option that shows up is a already completed history class but i need it to do my english class

**Comment by ITAC85v2** [comment]
How many classes did you purchase?

**Comment by GSRHackZ** [comment]
Contact 9295845325

**Comment by studiossn** [comment]
the person said it was the wrong number, also im sorry it took so long to
reply

**Comment by GSRHackZ** [comment]
make sure you entered the correct number when contacting. The number I have entered above is not incorrect
