### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by dennnny** [GSRHackZ/EdgyBot_Edgenuity_Bot#188]
Will tell me my login is incorrect. I have proof of verification and payment. Login credentials are the same ones I made my acc with so I know they’re correct.

**Comment by GSRHackZ** [comment]
Contact 9295845325 and u probably entered the wrong initials

**Comment by dennnny** [comment]
I Didnt :)

**Comment by dennnny** [comment]
Is there any way I can send picture proof that it’s right
