### ISSUE TITLE
Problem 

### ISSUE THREAD

**Issue by rricky24** [GSRHackZ/EdgyBot_Edgenuity_Bot#189]
I just bought a class less than an hr ago my cashapp was $rricky24, i just have one class and it says “this class is not part of your payment plan” so I can’t use it. I made sure to download tampermonkey and the latest version of edgybot. Are you able to activate it or can I get a refund really trying to finish this class it’s algebraic reasoning b.

**Comment by GSRHackZ** [comment]
click alt r and reset bot then login again
