### ISSUE TITLE
I bought twice seperately for the same account

### ISSUE THREAD

**Issue by rrugrrats** [GSRHackZ/EdgyBot_Edgenuity_Bot#194]
I have bought and used the bot on one account for $30. I wanted to buy again, and I pressed reorder, which prompted me to pay the $30 again, but now it's not letting me pick another class I paid for. It keeps saying to sign into Edgunuity which I am doing but no further prompts are being given even though I paid for the second class. If you want any information on the order confirmation or if there is anything you can do manually I would really appreciate that. And I also wonder why there is an extra payment for each class make it a lump sum payment since the bot doesn't let you use it on different accounts and maybe increase the price a bit so things like this don't happen.

**Comment by GSRHackZ** [comment]
contact 9295845325
