### ISSUE TITLE
Edgybot not working on literature classes.

### ISSUE THREAD

**Issue by 3hqm** [GSRHackZ/EdgyBot_Edgenuity_Bot#196]
When I let the automation do its thing, the bot never finds the answer, but I manually search for the classes and find the solutions.

**Comment by GSRHackZ** [comment]
Check story on instagram, account: gsrhackz
Solution: reinstall chrome (yes, the whole browser)

**Comment by MarcREXRED** [comment]
My Edgy bot is not verified as of yet says can you verify my boy that I purchases cash ta $MarcGregorelerebours sent cash for the bot to you GSRHackZ says need a veriftication verified for the bot for accont Marc-Gregore
