### ISSUE TITLE
please read

### ISSUE THREAD

**Issue by 24motyson80** [GSRHackZ/EdgyBot_Edgenuity_Bot#201]
It never redirected me to a new page after putting in how many classes I want and my cashapp info. it never gave me a payment method after I pressed continue

**Comment by GSRHackZ** [comment]
Send a video of this issue, it's hard to understand exactly what you mean 🙏

**Comment by 24motyson80** [comment]
![76A0895D-5CE6-43AE-A6C6-32A89DC316BE](https://user-images.githubusercontent.com/132153861/235312977-9f8f918f-34da-4b21-9273-20405b0fecc4.jpeg)

**Comment by 24motyson80** [comment]
I never got the payment instructions, and it’s not letting me put a video down I’ll try again

**Comment by 24motyson80** [comment]
Im so confused
