### ISSUE TITLE
Edgy Bot Not verified can you guys verify the account that i Purchased

### ISSUE THREAD

**Issue by MarcREXRED** [GSRHackZ/EdgyBot_Edgenuity_Bot#202]
My Edgy bot is not verified as of yet says can you verify my boy that I purchases cash ta $MarcGregorelerebours sent cash for the bot to you GSRHackZ says need a veriftication verified for the bot for accont Marc-Gregore

**Comment by GSRHackZ** [comment]
Contact 9295845325
