### ISSUE TITLE
quiz and test

### ISSUE THREAD

**Issue by zayfox24** [GSRHackZ/EdgyBot_Edgenuity_Bot#211]
I made a post about how it cant find any answers since the new updates and I was told to uninstall Chrome. I did that and it didn't work. It only has happened since last 2 updates. If you could look into it that would be great since rn Im paying to do it myself

**Comment by GSRHackZ** [comment]
Gotchu, lmk how today's later update helps you out. 

Also EdgyBot's selling point isn't really quizzes or tests, more of the automation of ungraded activities. but I digress
