### ISSUE TITLE
Answering ALL Questions Wrong.

### ISSUE THREAD

**Issue by IDontGiveAFuck0** [GSRHackZ/EdgyBot_Edgenuity_Bot#212]
I just purchased EdgyBot and it has not passed a single assignment at all. What can I do to fix this? Also, the bot wasn't in full automation when it was failing my assignments.

**Comment by GSRHackZ** [comment]
It says assignments are not supported in the description. The semi support isn't even a selling point of the product. If you are talking abt it guessing on warm-ups & etc, it's supposed to.
