### ISSUE TITLE
can’t find any answers 

### ISSUE THREAD

**Issue by cel38892** [GSRHackZ/EdgyBot_Edgenuity_Bot#217]
ever since the last few updates, it apparently can’t find any answers online in any subject, even in subjects where in the past it’d 100% quizzes and tests on full auto. i’ve tried uninstalling and reinstalling chrome, tampermonkey, and even the edgybot files but nothing seems to be working. pls help :(

**Comment by GSRHackZ** [comment]
> ever since the last few updates, it apparently can’t find any answers online in any subject, even in subjects where in the past it’d 100% quizzes and tests on full auto. i’ve tried uninstalling and reinstalling chrome, tampermonkey, and even the edgybot files but nothing seems to be working. pls help :(

Have to delete all browser data before uninstalling

Has been tested by multiple users for the latest version v3.45
