### ISSUE TITLE
Edgybot "Answer cannot be found"

### ISSUE THREAD

**Issue by mbartlett600** [GSRHackZ/EdgyBot_Edgenuity_Bot#224]
When I first started using Edgybot it worked on almost every question but now it always says answer cannot be found and has me do a manual search. Is there any way to fix this?

**Comment by GSRHackZ** [comment]
Yes. The only way to fix this, at least that we know of, is to remove all browsing history on chrome along with cache & cookies and then reinstall chrome and EdgyBot
