### ISSUE TITLE
EdgyBot

### ISSUE THREAD

**Issue by eatingthechicken123** [GSRHackZ/EdgyBot_Edgenuity_Bot#228]
Can I get some help with something, I paid 60 dollars for 4 classes, but the way mine was setup was that it gives me one class at a time so I only chose one class but I thought it would later let me add it to another class. But I was just wondering, my next class is intro to art, and when I try to select my class for the bot, it's not appearing. I was wondering what's going on or is it the fact we can't use the bot for the class. Please respond asap

**Comment by eatingthechicken123** [comment]
![image](https://github.com/GSRHackZ/EdgyBot_Edgenuity_Bot/assets/133458116/ee112f46-cfba-4c46-a4ea-a5a0c605c4c3)
theres only 1 class on the drop down menu, is it that we can't use the bot for the specific class

**Comment by eatingthechicken123** [comment]
Sorry for the confusion I just installed it today, and I really like it so far. I'm just wondering if we can use the bot for this art class or no?

**Comment by eatingthechicken123** [comment]
Sorry I think I figured it out, it's alt + r. I'm sorry about that.

**Comment by GSRHackZ** [comment]
no worries
