### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by unicorn923** [GSRHackZ/EdgyBot_Edgenuity_Bot#231]
I have the bot updated to 3.54 but it keeps telling me to update it even when it is up to date, when i click cancel it logs me out and I don't know my login

**Comment by unicorn923** [comment]
I made a mistake that I am on 3.53 but when I click update, it doesn't change it to 3.54

**Comment by GSRHackZ** [comment]
Uninstall tampermonkey and reinstall this will fix the issue

**Comment by unicorn923** [comment]
I reinstalled but now I have to re-login to the bot when logging in to Edgenuity and I don't know my login.
