### ISSUE TITLE
few issues

### ISSUE THREAD

**Issue by heroenfather** [GSRHackZ/EdgyBot_Edgenuity_Bot#232]
i have a few issues, one being i needed to refund because i was going to buy 2 classes but realize it wouldnt work since they only assign me one class at a time so i needed to refund to pay for one class at a time, which i understand because it says no refunds but a little neogtiation or exception would of been nice to hear.

but as far as that, i cant even use the classes i bought because it only shows a class i bought previously when i should have two additional classes, ive tried to uninstall and reinstall the bot but it doesnt work. how do i fix this because not only did i not mean to pay for two classes, i cant even use them.

**edit: i managed to reset everything but since im only given one course at a time, it will only show one class that i can pick, will i be able to choose another one once im done with this class?? because it seems like i cant from the dropdown menu. i will be really upset if i payed $40 for one class basically.**

**Comment by GSRHackZ** [comment]
I think I dealt with this already, if not contact 9295845325
