### ISSUE TITLE
Invalid Script Header & Log in page not coming up

### ISSUE THREAD

**Issue by ShayeraStan** [GSRHackZ/EdgyBot_Edgenuity_Bot#234]
Keep getting an Invalid Script header and the log in page wont come up. I already paid for it btw

**Comment by linkmoss000** [comment]
I also had the "Invalid Script header" issue when installing EdgyBot, but it was on a new and different PC. I paid also, but my login page showed up for me though.

This is the quick fix that worked for me:
GSRHackZ > EdgyBot_EdgenuityBot > edgyBot.user.js > click on "Copy raw contents" and paste it into Tampermonkey.

**Comment by ShayeraStan** [comment]
Where do I paste it? Ive never used tampermonkey before until now.
