### ISSUE TITLE
EdgyBot shows that its activated but is not working

### ISSUE THREAD

**Issue by kylejnavarro** [GSRHackZ/EdgyBot_Edgenuity_Bot#236]
When I click on tampermonkey its shows that the bot is turned on. But when I'm in edgenuity its not showing. Like it goes to a class that I picked to do the work but it doesn't do anything and it just continues on as it were normal without the bot. Then every time i try and go back to the edgenuity screen with all my classes it just takes me back to the assignment it wants to work on.

**Comment by ShwiftyClaps** [comment]
I wanna say its been detected or something because im having the same issue it only works without the bot and it will stop pulling you into that class if you turn off tamper monkey

**Comment by ZTGTHEGAMER** [comment]
Im having the same issue i think it been detected but teah it wont wven show up anymore this suck so close to graduation 


It was working fine but just not working at all now i gotta try to push through without 😭

**Comment by ShwiftyClaps** [comment]
yea straight ass but nothing we can do if its been detected on our accounts

**Comment by ShwiftyClaps** [comment]
Unless its just buggin right now I hope thats the case

**Comment by AndrewCorbin1** [comment]
same thing for me I hope it gets fixed

**Comment by ShwiftyClaps** [comment]
damnnnnn no way they crackin down

**Comment by ShwiftyClaps** [comment]
anyone try reinstalling chrome?

**Comment by AndrewCorbin1** [comment]
nah not yet

**Comment by ShwiftyClaps** [comment]
@GSRHackZ

**Comment by ShwiftyClaps** [comment]
Id try that if it dosen't work i think were cucked

**Comment by GSRHackZ** [comment]
The bot has been patched along with most Edgenuity related scripts. For me to make it work again, if I can, it will take a while 😭

**Comment by ShwiftyClaps** [comment]
NOOOOOOOOOOOOOO

**Comment by ShwiftyClaps** [comment]
How is that even detectable

**Comment by ShwiftyClaps** [comment]
and also a time frame i got 9 days to finish LMFAO

**Comment by kylejnavarro** [comment]
My luck I just got it today and now they patched it the same day

**Comment by AndrewCorbin1** [comment]
same I got it an hour ago

**Comment by ShwiftyClaps** [comment]
we pray gsr pulls some ace moves and get us back online

**Comment by GSRHackZ** [comment]
Nevermind, fixed it. Releasing update now

**Comment by ShwiftyClaps** [comment]
Wait so are we good?

**Comment by ZTGTHEGAMER** [comment]
@GSRHackZ well if you can fix it hit me up when the update out please

**Comment by ShwiftyClaps** [comment]
Someone @ me mine is still broke

**Comment by kylejnavarro** [comment]
Im pretty sure there still working on it i would just wait a little

**Comment by ShwiftyClaps** [comment]
ima leave this open lmk when its back up

**Comment by GSRHackZ** [comment]
Fixed in latest version 3.57

**Comment by ZTGTHEGAMER** [comment]
@GSRHackZ ima name my kid after you

**Comment by ShwiftyClaps** [comment]
Much appreciated mannn💜
