### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by jj833519** [GSRHackZ/EdgyBot_Edgenuity_Bot#237]
I went through all the instructions as they were and looked through some other feedback and don’t know why but I can’t login my payment was verified it said but when I put in credentials and try to click login nothing happens I just updated ur to v3.57  and seen when ut took me to my tamper monkey installed scripts there is an error in there it’s saying like something like dot notation

**Comment by buzzskywalker** [comment]
Same issue here.

**Comment by GSRHackZ** [comment]
contact 9296737008
