### ISSUE TITLE
Bug/Issue: Doesn't solve drop-down box or open-ended answers / Unable to freely move throughout questions

### ISSUE THREAD

**Issue by linkmoss000** [GSRHackZ/EdgyBot_Edgenuity_Bot#238]
Version: v3.57

Note: This was tested only on an elective class.

**_Quizzes_**: whether the full auto is on or not, it does not solve drop-down box answers. 
**_Practices_**: whether the full auto is on or not, it does not solve open-ended questions. Also sometimes, If the first or sixth question is open-ended (in my instance), it may go to the next to the next question and simply stay there and not answer... whether it is full auto or not.

**_On both Quizzes & Practices_**: whether the full auto is on or not, it sometimes doesn't answer the last or second to last question. Also, it doesn't completely skip as in "skip-over" the answers it cannot solve. It first lands on the question, skips, it leaves the question box highlighted for a fraction of a second, then immediately unhighlights the box. (Then it might continue a cycle of continually auto-answering because of course some question(s) are not solved)

I basically had to keep turning EdgyBot off, and repeat the proccess.. or I could solve the drop-down/open-ended questions first then turn on edgybot. Mainly because the new auto-answer feature kept continuously moving on to the next question and would not let me answer the unanswered questions. I remember we had the feature to move freely and jump questions while EdgyBot was still on, in the previous versions.

**Comment by Demolicity** [comment]
I second this.

**Comment by GSRHackZ** [comment]
fixed, enjoy
