### ISSUE TITLE
account not there?

### ISSUE THREAD

**Issue by cacahead101** [GSRHackZ/EdgyBot_Edgenuity_Bot#241]
i tried logging in on edge with the bot and i put in the correct ussername and password multiple time and it brings me to a new tab telling me my account doesnt exist??? man i just paid sm for this just for it to not even let me log in KMS.

**Comment by buzzskywalker** [comment]
Having this issue, except it doesn't even bring me to a new tab.

**Comment by GSRHackZ** [comment]
contact 9296737008
