### ISSUE TITLE
My edgy bot isnt working 

### ISSUE THREAD

**Issue by kevy900800** [GSRHackZ/EdgyBot_Edgenuity_Bot#247]
hello i bought 4 classes and all 3 of them have been working flawlessly its just this forth one wont answer questions on quizez or even give me the answers its like doing it on my own is there a way i can fix this asap

**Comment by macmase** [comment]
same problem litterally last class and it wont do quizes

**Comment by GSRHackZ** [comment]
fixed in v4.1
