### ISSUE TITLE
Bug/Issue?

### ISSUE THREAD

**Issue by J-Vel** [GSRHackZ/EdgyBot_Edgenuity_Bot#251]
The bot keeps looping videos and freezes there until you exit the activity then when you go back in it the bot loops the video again

**Comment by J-Vel** [comment]
or sometimes it will refresh the page and just keep looping the video

**Comment by Merasame** [comment]
> The bot keeps looping videos and freezes there until you exit the activity then when you go back in it the bot loops the video again

I second this, and the answer search doesn't work anymore

**Comment by GSRHackZ** [comment]
fixed, edgybot v3.42
