### ISSUE TITLE
On the quizzes the auto answer isn't working or when its off

### ISSUE THREAD

**Issue by kylejnavarro** [GSRHackZ/EdgyBot_Edgenuity_Bot#260]
It shows that its looking for an answer but then doesn't pick anything usually before it will pick the answers right away but now it doesn't . I tried reinstalling and everything and that still didn't work so im not sure what to do.

**Comment by GSRHackZ** [comment]
Contact 9296737008

**Comment by kylejnavarro** [comment]
> Contact 9296737008
Sorry i don't mean to be impatient but how long am i expected to wait to get a message back with this number? it's been a couple hours

**Comment by kylejnavarro** [comment]
never mind gsr i got it fixed thanks

**Comment by Jae1yn1** [comment]
how did you get it back to normal?
