### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by Jae1yn1** [GSRHackZ/EdgyBot_Edgenuity_Bot#261]
edgybot wont answer any of the questions on my quizzes anymore, before it would answer all the questions a id get 100%, now even with auto turned off it just sits there.

**Comment by GSRHackZ** [comment]
Contact 9296737008

**Comment by Jae1yn1** [comment]
its been 3 days since i reached out to the number and still no response, can you just tell me if i need to like trouble shoot it. my class ends soon so im kinda in a hurry this is a little inconvenient ngl

**Comment by Jae1yn1** [comment]
my issue was never solved :(
