### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by kylejnavarro** [GSRHackZ/EdgyBot_Edgenuity_Bot#264]
@GSRHackZ Once again the quizzes, unit tests, exams aren't working I reached out to the number and I get no response so im just trying to figure out what's wrong?

**Comment by GSRHackZ** [comment]
it means the class needs answers scraped. Reply here with the class name

**Comment by kylejnavarro** [comment]
@GSRHackZ the class name is CA-Principles of American Democracy Mr. Baugh IS 22-23 Semester 2

**Comment by GSRHackZ** [comment]
contact 9296737008
