### ISSUE TITLE
Small Bug

### ISSUE THREAD

**Issue by ChaoticCow** [GSRHackZ/EdgyBot_Edgenuity_Bot#266]
![image](https://github.com/GSRHackZ/EdgyBot_Edgenuity_Bot/assets/128778180/f8699dab-651c-435f-aff0-0cec1c657a0f)
Basically, the opacity of the ui both here and before the class is lowered. Dont know what caused it but it started up randomly and hasnt reverted.

**Comment by ITAC85v2** [comment]
This is intentional functionality. Simply click on the "EdgyBot v4.25" text and it will be fixed.
