### ISSUE TITLE
Need to buy another class

### ISSUE THREAD

**Issue by Shaaadddd** [GSRHackZ/EdgyBot_Edgenuity_Bot#276]
i already have the edgybot installed and i have it working on some of my classes, but i need to buy more. Do i have tl go through the whole process and buy the bot again?

**Comment by ITAC85v2** [comment]
Contact (929) 673-7008 for assistance on adding classes to your account.

**Comment by m3lyodas** [comment]
i would like to purchase another class aswell but the number hasnt responded
