### ISSUE TITLE
Paid for another class

### ISSUE THREAD

**Issue by Shaaadddd** [GSRHackZ/EdgyBot_Edgenuity_Bot#277]
I just paid another $10 for an extra class but my bot isn't letting me choose a new class for it to work on. Needed it to do a physics class but when i click on the class it says "this class is not part of your payment plan". I saw gsr respond to a diff person who needed another class and said to follow the purchasing process again and only send the amount for the extra class and that's what I did.

**Comment by Shaaadddd** [comment]
And I texted the number that you guys say to reach out to about an extra class but i havent gotten an answer or anything

**Comment by enjadia** [comment]
this same thing happened to me, i initially had bought 4 classes but then i was assigned more classes (3) and then purchased that many more.

**Comment by ITAC85v2** [comment]
Press ALT + R to reset EdgyBot, then you should be able to pick your new classes.

**Comment by GSRHackZ** [comment]
This is all due to not following class addition instructions. Contact 9296737008 if u still have issues.
