### ISSUE TITLE
this class is not apart of your payment plan

### ISSUE THREAD

**Issue by cwhiz7** [GSRHackZ/EdgyBot_Edgenuity_Bot#278]
i paid for biology class, and surely picked biology. and now its saying its not apart of my payment plan. and now everytime i go to edgenuity edgybot doesn't even pop up anymore

**Comment by A7mad137** [comment]
I have the same problem I paid for 3 classes but for the other class it says this is not part of ur edgy plus plan

**Comment by GSRHackZ** [comment]
Contact 9296737008
