### ISSUE TITLE
Auto & assigments bad/notworking

### ISSUE THREAD

**Issue by BurstyBeVibn** [GSRHackZ/EdgyBot_Edgenuity_Bot#279]
Quizzes work fine in fact seems to be Perfect

Instruction Does not auto advance nor does it even select anything or give me answers or anything

maybe its not supposed to be doing thoese things but id asume it is supposed to do that 

If it is supposed to do it and for some reason isnt 
Class name =  5326 CR Practical English 11

**Comment by BurstyBeVibn** [comment]
fixed js had to refresh 

But Assigments give bad answers and the format is all messed up like the answer it gives isnt direct to where u can look at it and get the answer

**Comment by BurstyBeVibn** [comment]
![image](https://github.com/GSRHackZ/EdgyBot_Edgenuity_Bot/assets/125935567/d580fea0-9911-49a8-b834-1903ec90db58)

here u can see what i mean also dosent advance when i click somthing, so overall the toll is good but for assigments its not the best is there a fix for this or it js isnt made for assigments?

**Comment by GSRHackZ** [comment]
Maybe check the description of the bot, assignments aren't even supposed to have any support at all. This is like a prototype assignment support.
