### ISSUE TITLE
Bug/Issue: Near-Instant Instruction time while using EdgyBot

### ISSUE THREAD

**Issue by linkmoss000** [GSRHackZ/EdgyBot_Edgenuity_Bot#33]
Script Version: v2.1982
Description: The Total Time an Instruction is completed when using EdgyBot is within a single and double digit second window. (ex: 7sec or 11sec). This only targets Instructions. Instructions have video slides (multiple or not) with at least 30 sec-10 mins for completing the video slide. This Bug/Issue occurs either every few instructions or it may happen consecutively for a while then stop for a while.

Note: It is strictly on Instructions. Not warm-ups, summaries, or anything else.
Note: I am aware that the bot doesn’t control that, it is just Edgenuity’s counter. And how Edgenuity's Timer resets after every refresh.

![download](https://user-images.githubusercontent.com/116431940/212496032-121ce3e1-5e52-42e0-a0f0-e48ec1d8fa4f.png)

Potential Solutions:
1. Create an amount of time that it waits before submitting the entire activity and then moving on to the rest.
2. Add very generous time intervals between slides and test/quiz questions. (20 seconds per slide/question)
Or
3. Find Edgenuity’s Timer and tweak it

**Comment by GSRHackZ** [comment]
Thank you, will make sure to have this fixed soon. 🙏

**Comment by wearrrrr** [comment]
Ideally we would just want to wait a non suspicious amount of time, say 20-30 seconds, which could probably be done with a setTimeout. We could also wait for a certain amount of api calls to the timer that edgenuity uses, because that is server side.

**Comment by GSRHackZ** [comment]
EdgyBot v3.0 is out.  Couldn't have been done without @ITAC85v2 😊
