### ISSUE TITLE
Issue: No clarification if paying for unloaded courses is pointless. (With the current course verification method)

### ISSUE THREAD

**Issue by linkmoss000** [GSRHackZ/EdgyBot_Edgenuity_Bot#34]
Script Version: v2.1982 (It says v2.198 on the screen though but it says v2.1982 in TamperMonkey)
Description: I just paid for multiple courses, but there are unloaded courses that I paid for. It used to be required that you name your courses during the payment process before payment but you removed that option recently. 

![download](https://user-images.githubusercontent.com/116431940/212499316-3bb9a4cd-1347-437f-a6e0-db85245a200f.png)

Possible solutions: 
- You should either resort back to the previous course verification method where we gave the names of our courses.
or
-  Clarify if someone has paid for courses that aren't loaded in their Edgenuity yet during the selection (If using the current method)

If you continue with the current method.
Add information somewhere in the selection page and/or on a chrome message box.
Something Like:
“You can pay for multiple courses even if they are not loaded into your Edgenuity Course List yet."
"Don't be afraid to select/confirm existing current courses you have now, then select/confirm the remaining non-loaded courses that you paid for when they become available later."
"But you can’t go back and change your choice once it has been picked”

**Comment by wearrrrr** [comment]
You actually can go back and change the choice, you have to factory reset your edgyBot and re-enter the product key though, I can work on implementing a way to reset just the chosen classes, but it would have to be carefully coded.

**Comment by linkmoss000** [comment]
Thank you. And that does sound like a good idea too.

**Comment by drown21k** [comment]
> You actually can go back and change the choice, you have to factory reset your edgyBot and re-enter the product key though, I can work on implementing a way to reset just the chosen classes, but it would have to be carefully coded.

hey wearrrrr do you have social media i have a question

**Comment by cincy513** [comment]
> You actually can go back and change the choice, you have to factory reset your edgyBot and re-enter the product key though, I can work on implementing a way to reset just the chosen classes, but it would have to be carefully coded.

How do you factory reset it???

**Comment by GSRHackZ** [comment]
EdgyBot has been patched. 🤔<br>
My instagram account has been taken down for copyright, some bs about the Edgenuity logo showing in one of my highlights. 🙄<br>
EdgePlus site is down for obvious reasons (can't be accepting orders and payment for a non-functioning product). 🤨<br>
Possible ETA of EdgyBot v3.0: End of this month (February) 🤞

**Comment by GSRHackZ** [comment]
EdgyBot v3.0 is out.  Couldn't have been done without @ITAC85v2 😊
