### ISSUE TITLE
Bug/Issue: Edgenuity crashes when EdgyBot is left on and fully automatic. 

### ISSUE THREAD

**Issue by linkmoss000** [GSRHackZ/EdgyBot_Edgenuity_Bot#35]
Script Version: v2.1982
Description When EdgyBot is left on fully automatic, It does tend to crash sometimes after a few hours. activity The time range is usually 1-5 hours before it crashes. It happens 90% of the time out (throughout my entire time I have been using EdgyBot) when left on automatic.

![ezgif-4-7b3a045eab](https://user-images.githubusercontent.com/116431940/212500976-c415d564-d30f-4547-9ecd-8545357f5c4b.jpg)

![ezgif-4-229ae9c368](https://user-images.githubusercontent.com/116431940/212501229-dd2dd960-d5e8-4b32-9c39-868e5738f905.png)

Note: I just recently got an AdBlock Extension but I forget if it was before or after this Bug/Issue started happening. (But I did turn it off for Edgenuity, I just don’t know when… and if it solved or created issues).

**Comment by wearrrrr** [comment]
If possible could you send a screenshot of what the devtools console looks like before a crash happens? That would really help to figure out what is going on, but this seems like an issue with edgenuity's servers, and not something we could solve.

**Comment by linkmoss000** [comment]
@wearrrrr Will do.

**Comment by GSRHackZ** [comment]
EdgyBot v3.0 is out.  Couldn't have been done without @ITAC85v2 😊
