### ISSUE TITLE
Warm-up bug

### ISSUE THREAD

**Issue by saikat313** [GSRHackZ/EdgyBot_Edgenuity_Bot#36]
Every time I press start for EdgyBot to do my warm-ups, it says that they are all finished even though edgybot didn't do it at all, i'd have to manually disable edgybot to do it manually.

**Comment by GSRHackZ** [comment]
it means you have pretests, select quiz mode instead and do pretests. if that's not the case, contact me on Instagram @gsrhackz and i'll help u out.
