### ISSUE TITLE
Bug/Issue: Near-Instant Online Content time while using EdgyBot

### ISSUE THREAD

**Issue by linkmoss000** [GSRHackZ/EdgyBot_Edgenuity_Bot#38]
Script Version: v2.1983
Description: The total time an Online Content is completed is ONLY 7 or 8 seconds when using EdgyBot. I notice it goes on a streak of 8 and then occasionally 7. 

Note: There hasn't been any problem with the % that Online Content gets. It has been constantly and only scoring 100%. (During the Bug/Issue)
Note: I know it shows the vocabulary at 10sec but that is because it had one word to fill in. There hasn't been any issues with Vocab.
Note: Edgenuity's Estimated Time for Online Content is 15min.

![ezgif-1-765339c304](https://user-images.githubusercontent.com/116431940/214141210-fabd1d96-1415-4c4b-85bd-a5899f2fb029.jpg)

**Comment by drown21k** [comment]
hey linkmoss do you have instagram i have question

**Comment by ITAC85v2** [comment]
Since EdgyBot refreshes often on these assignments, it makes it think that you spent very little time on the assignment (bug with Edgenuity, not EdgyBot). The timer could theoretically be forged/faked, but it's not a guarantee.

**Comment by GSRHackZ** [comment]
EdgyBot v3.0 is out.  Couldn't have been done without @ITAC85v2 😊
