### ISSUE TITLE
Instagram

### ISSUE THREAD

**Issue by Oranjihea** [GSRHackZ/EdgyBot_Edgenuity_Bot#43]
is there an updated Instagram to contact customer support?

**Comment by cincy513** [comment]
i think his insta got took down and the site is down

**Comment by GSRHackZ** [comment]
EdgyBot has been patched. 🤔<br>
My instagram account has been taken down for copyright, some bs about the Edgenuity logo showing in one of my highlights. 🙄<br>
EdgePlus site is down for obvious reasons (can't be accepting orders and payment for a non-functioning product). 🤨<br>
Possible ETA of EdgyBot v3.0: End of this month (February) 🤞

**Comment by GSRHackZ** [comment]
EdgyBot v3.0 is out.  Couldn't have been done without @ITAC85v2 😊
