### ISSUE TITLE
What happen to yo insta??

### ISSUE THREAD

**Issue by cincy513** [GSRHackZ/EdgyBot_Edgenuity_Bot#44]
Plus what happen to the site why is it down?

**Comment by PopDoed** [comment]
Is the bot not working for everyone else rn?

**Comment by cincy513** [comment]
> Is the bot not working for everyone else rn?

hasnt been workin for 2 days

**Comment by GSRHackZ** [comment]
EdgyBot has been patched. 🤔<br>
My instagram account has been taken down for copyright, some bs about the Edgenuity logo showing in one of my highlights. 🙄<br>
EdgePlus site is down for obvious reasons (can't be accepting orders and payment for a non-functioning product). 🤨<br>
Possible ETA of EdgyBot v3.0: End of this month (February) 🤞

**Comment by GSRHackZ** [comment]
EdgyBot v3.0 is out.  Couldn't have been done without @ITAC85v2 😊
