### ISSUE TITLE
login & bad grades

### ISSUE THREAD

**Issue by studiossn** [GSRHackZ/EdgyBot_Edgenuity_Bot#56]
i dont remeer setting up a login but i do still have access to my edgy bot on my original pc can i reset it up from there or edit it also the bot is giving me bad grades is there any fix for these to

**Comment by ITAC85v2** [comment]
If you don't remember your login, create a new account. As to getting bad grades, you need to provide details on what types of lessons/activities you're getting poor grades on, and what grade you're getting on them.

**Comment by studiossn** [comment]
The assignments that it’s failing are quizzes and unit test

**Comment by GSRHackZ** [comment]
> The assignments that it’s failing are quizzes and unit test 

We are working on this. But if the classes it's failing are math related, please click the restrict automation button while it's doing a quiz/test and do it urself.

**Comment by GSRHackZ** [comment]
Fixed incorrect answers and bad grades issue. Update to v2.34 🙏
