### ISSUE TITLE
No Account found

### ISSUE THREAD

**Issue by Disconnected55055** [GSRHackZ/EdgyBot_Edgenuity_Bot#58]
I did everything right on your edgybot website, entered a all my info and i made an account and i put my username and password in, But when i went to my edgenuity it asks me to log in but when i try it says "error occured account info is incorrect" or something along those lines. Can you help??

**Comment by GSRHackZ** [comment]
Make sure your account information is correct when you are logging in. this either means your password or username is incorrect.
