### ISSUE TITLE
Submit delay issue

### ISSUE THREAD

**Issue by quotet** [GSRHackZ/EdgyBot_Edgenuity_Bot#60]
When I set submit delay for 5 minutes it counts down from 300 seconds but before it finishes it exits the activity and goes back into it and restarts the counter

**Comment by ITAC85v2** [comment]
Which lesson(s) does this occur on? What course(s) are you taking in which this bug occurs in?

**Comment by GSRHackZ** [comment]
I think I know what the issue is

I'll look into it today 👌

**Comment by quotet** [comment]
Thank you for looking into @GSRHackZ and @ITAC85v2 it happens in any course or activity for me like I will set timer for 5 minutes it will quit the activity around 60 seconds left on the timer and then go back into the activity and reset the timer
