### ISSUE TITLE
Not working got this warning 6 times 

### ISSUE THREAD

**Issue by whereswaldo3** [GSRHackZ/EdgyBot_Edgenuity_Bot#61]
![Screen Shot 2023-03-06 at 11 00 13 AM](https://user-images.githubusercontent.com/127128353/223164069-4a420721-4c32-4392-991e-64574e2b3433.png)

**Comment by ITAC85v2** [comment]
Lessons named "Assignment" aren't supported at this time.

**Comment by whereswaldo3** [comment]
it’s biology would it still not workSent from my iPhoneOn Mar 6, 2023, at 1:11 PM, ITAC85v2 ***@***.***> wrote:﻿
Lessons named "Assignment" aren't supported at this time.

**Comment by GSRHackZ** [comment]
He said activities with the name "assignment" don't work. That ahs nothing to do with the class name. It's for any class @whereswaldo3
