### ISSUE TITLE
EdgyBot not working for Spanish 1

### ISSUE THREAD

**Issue by KOOPERGOSSETT1** [GSRHackZ/EdgyBot_Edgenuity_Bot#64]
EdgyBot not working for Spanish 1

The bot does not work on the videos and activities for Spanish 1.

**Comment by GSRHackZ** [comment]
> EdgyBot not working for Spanish 1
> 
> 
> 
> 
> 
> The bot does not work on the videos and activities for Spanish 1.
> 
> 
> 
> 

Foreign language classes not supported at the moment
