### ISSUE TITLE
edgybot

### ISSUE THREAD

**Issue by thaviin** [GSRHackZ/EdgyBot_Edgenuity_Bot#68]
i strongly suggest removing bing from the search engines it uses because it gives alot more incorrect answers now compared to before

**Comment by GSRHackZ** [comment]
Working on this. The issue is not bing, it's the auto answer function.

**Comment by joice2fine** [comment]
i dont know how to use this. pls help me

**Comment by GSRHackZ** [comment]
Instructions are here: https://github.com/GSRHackZ/EdgyBot_Edgenuity_Bot/wiki/How-to-install-EdgyBot

FAQ is here: https://github.com/GSRHackZ/EdgyBot_Edgenuity_Bot/wiki/Q&A

We don't help users set it up because all instructions have been written out for you, following these steps is not hard.
