### ISSUE TITLE
bot types "random_plugin" into text boxes

### ISSUE THREAD

**Issue by sam6taylor** [GSRHackZ/EdgyBot_Edgenuity_Bot#70]
whenever i have a response box on an english instruction the bot will type "random_plugin" into the box... obviously a human would never say that so it makes it obvious affff

![image](https://user-images.githubusercontent.com/127810059/224876891-f1ad12b3-aa31-46a1-9428-3bc9a891dbad.png)

**Comment by GSRHackZ** [comment]
On purpose, these questions aren't graded. It was either that or just reentering the question, either way it would get the question wrong. I guess We can make it write something more human.

**Comment by sam6taylor** [comment]
Usually it just leaves it blank and gets it wrong. Which is completely fine. I just don't like that it types something at all, especially something that a human would never type in there, making it super obvious if a teacher ever saw it.
