### ISSUE TITLE
doesnt open

### ISSUE THREAD

**Issue by master1777** [GSRHackZ/EdgyBot_Edgenuity_Bot#72]
this is so annoying when I go onto https://www.edgenuity.com/ it shows on tampormonky a red 5 but the bot doesn't open.

**Comment by ITAC85v2** [comment]
You need to log in first, which will bring you to student.edgenuity.com. From there, the bot will work.
You also must activate the bot first. Instructions can be found [here](https://github.com/GSRHackZ/EdgyBot_Edgenuity_Bot/wiki/How-to-install-EdgyBot).

**Comment by master1777** [comment]
I did as the Instructions say but I cant see the bot.

**Comment by ITAC85v2** [comment]
Please attach screenshots or recordings of your issue, I need more info.

**Comment by GSRHackZ** [comment]
umm.... you need to login first? as in go to your dashboard for classes. Did you do that? If so please send screenshots of the dashboard being open along with tampermonkey being enabled. Also click on the puzzle icon, top right of your browser, and click tampermonkey, the send a screenshot of all enabled scripts.

**Comment by master1777** [comment]
I don't know how to send a screen shot to you.

**Comment by master1777** [comment]
how would I send you a screenshot.

**Comment by GSRHackZ** [comment]
Get the requested pictures and send them here. Copy the images and paste them.
Having issues? You can also try doing this:

You can host the images online and send them here, as links.

You can try using this: https://ctrlq.org/images/

**Comment by master1777** [comment]
https://www.linkpicture.com/q/Screenshot-49_2.png
can you see the picture?

**Comment by GSRHackZ** [comment]
This means the class is not part of your payment plan. Can you send the requested pictures? This picture is not related to the issue you mentioned

**Comment by master1777** [comment]
https://www.linkpicture.com/view.php?img=LPic6414ddc478cef1092062910

**Comment by ITAC85v2** [comment]
Give me a sec, I might be able to help you now

**Comment by ITAC85v2** [comment]
What are the three classes you picked?

**Comment by master1777** [comment]
i picked two
ELA and biology

**Comment by ITAC85v2** [comment]
You were taking Language Arts. Reset EdgyBot by pressing the ALT and R key at the same time, then pick Language Arts.
