### ISSUE TITLE
Old class

### ISSUE THREAD

**Issue by itsjamelfr** [GSRHackZ/EdgyBot_Edgenuity_Bot#78]
https://user-images.githubusercontent.com/116363417/226504590-0355c03a-49bb-4058-b5db-f7363657dd77.MOV

Yo this Jamel from ig i seen your story so I didn’t dim you i have the single classes I need help because since the new update I didn’t do anything because I was at turkey but I paid for a new class and I didn’t use the edgy bot when I paid for it now I got the new class it still has my old class even tho I only get one each and I paid for a new one before the update and I need to start on my class

**Comment by GSRHackZ** [comment]
Explain that a bit better, what exactly do u need help with. adding a new class that you already paid for? pass me ur Instagram and i'll handle it there

**Comment by itsjamelfr** [comment]
My instagram is yaa_jamel it's because I buy one for each new class because I get single classes

**Comment by GSRHackZ** [comment]
You shouldn't do that, all you have to do is contact me to add a class for only $10, the base price is only once (for servers)

I will contact you on Instagram and we will sort this out
