### ISSUE TITLE
See edgybot account?

### ISSUE THREAD

**Issue by eeklolop** [GSRHackZ/EdgyBot_Edgenuity_Bot#79]
I made an edgybot account a while ago, and I have the script on operagx... I want to move it to chrome now, but I have no idea how to check my account details (username/password). Is there a way to do so, or am I just screwed?

**Comment by eeklolop** [comment]
And yes, I saw the comment saying to create a new account again, but I don't really want to pay $90 again..

**Comment by ITAC85v2** [comment]
I cannot guarantee EdgyBot will work on Opera GX. EdgyBot has only been tested on Chrome, so it may not work right or at all on Opera GX.

**Comment by GSRHackZ** [comment]
you don't have to pay, u can just login with your account on chrome. That's why we made a login system.

Login with your EdgePlus account on chrome after installing it there. 

Next time follow instructions, it clearly says chrome (many times)
