### ISSUE TITLE
Option Issue

### ISSUE THREAD

**Issue by killuaxisagi653** [GSRHackZ/EdgyBot_Edgenuity_Bot#80]
When using edgybot and clicking onto a class it asks you what you want edgybot to work on for example tests or quizzes or afk. I accidentally clicked all and I no longer get the option to pick. I looked everywhere and would like to find a way to open up that toolbar and pick my options.

**Comment by ITAC85v2** [comment]
Try going to any lesson and clicking "Stop EdgyBot".

**Comment by GSRHackZ** [comment]
Yeah stop the bot and it will give you that option again. or click the home button while doing an activity on the top right of your screen and it will also force stop the bot.
