### ISSUE TITLE
Login not working

### ISSUE THREAD

**Issue by mps3235** [GSRHackZ/EdgyBot_Edgenuity_Bot#81]
Evetime it pulls up the edge plus login i put my info in and it redirects me to a screen that just says payment has been verified but doesn't have the option for the bot to work on classes can anyone help me out? I'm up to date with tamper monkey and the edge bot and I paid

**Comment by ITAC85v2** [comment]
You must be on [student.edgenuity.com](https://student.edgenuity.com) to pick a class. If it isn't working, press the ALT and R key at the same time to reset EdgyBot, then try logging in again.
