### ISSUE TITLE
Sign in isn’t working 

### ISSUE THREAD

**Issue by Jmcintosh4** [GSRHackZ/EdgyBot_Edgenuity_Bot#83]
Ok so I was trying to do my work and the bot was glitching so I had uninstalled tampermoney and reinstalled it and updated the bot then that’s when I try to login it’s telling me username and password is wrong when it’s correct and I do t wanna have to rebuy something that I already bought 
![A2A8DFA1-5D9E-4621-80B5-9F073FC66A7D](https://user-images.githubusercontent.com/128565273/226798165-3ed23c33-93f3-4a6d-83e6-12f8807b3f81.jpeg)
Just showing you that I brought it to 
 #![1928D2B2-EAA1-4859-9D01-49F6631706FD](https://user-images.githubusercontent.com/128565273/226798221-6a8e531b-6184-4656-a3d8-9da5f1c7302f.jpeg)/ #77 #74

**Comment by GSRHackZ** [comment]
That's cuz ur logging in now, while servers are down. Try after 6:30am est and it will work
