### ISSUE TITLE
I paid 50 bucks and its not working 

### ISSUE THREAD

**Issue by David111803** [GSRHackZ/EdgyBot_Edgenuity_Bot#86]
I paid 50 bucks 5 days ago and I can't pick the classes I want I also have one class that I payed for and it was doing it now that I'm almost done its not doing it anymore in the bottom right it said bot with a green tag I've tried everything and it still doesn't work I paid 50 for this and its not working fix it

**Comment by GSRHackZ** [comment]
Contact 9295845325
