### ISSUE TITLE
Downloading Edgy Bot again  and need verify again after the shut dowwn

### ISSUE THREAD

**Issue by TravisKun** [GSRHackZ/EdgyBot_Edgenuity_Bot#88]
So I had pay 50 dollars for 3 classes For using Edgy bot But I had to uninstall since i deleted my chrome user which was my main Google acc from my mac I need help with verifying My stuff My name is JustbeingTravisjr@com I had payed Gsr 50 dollars for the hack and I do Have proof. Is there anyway I can be verifyed again?

**Comment by ITAC85v2** [comment]
If you remember your login info to EdgyBot, go to `student.edgenuity.com` and enter in your login. If not, I'll have to forward this to GSR as I do not manage the payments.

**Comment by GSRHackZ** [comment]
@TravisKun contact 929-584-5325

**Comment by TravisKun** [comment]
OKay i will

**Comment by mmcguffee** [comment]
Thank You again 🙂
