### ISSUE TITLE
edgybot afk will get stuck on retry and wont auto answer

### ISSUE THREAD

**Issue by geex1337** [GSRHackZ/EdgyBot_Edgenuity_Bot#89]

**Comment by ITAC85v2** [comment]
I need more info. What lesson(s) does this occur on? Could you provide a more detailed explanation of the issue?

**Comment by GSRHackZ** [comment]
Auto answer is clearly not supported for tests and quizzes, Anything else is fixed with a refresh of the page.  Please read the bottom of the instructions part on the wiki.
