### ISSUE TITLE
Edgybot Not Popping up.

### ISSUE THREAD

**Issue by ChaoticCow** [GSRHackZ/EdgyBot_Edgenuity_Bot#94]
So, im under the impression that the bot should show up somewhere on screen. Tampermonkey says a script was executed, but i dont see anything on my screen and it doesnt do anything in edgenuity. Whenever i start a class manually, tampermonkey says a script was executed 5 times.
Could it also be a problem with the fact that im using Time4Learning?

**Comment by GSRHackZ** [comment]
@ChaoticCow send pictures of your issue here. I need these few things to help you out:

* Picture of Tampermonkey being enabled along with script while Edgenuity tab is open
* Possible video of how you sign-in to edgenuity
* Better explanation of your issue

**Comment by GSRHackZ** [comment]
Without any additional info, I won't be able to help you with this issue. So please try your best at providing me with what was requested

**Comment by ChaoticCow** [comment]
https://user-images.githubusercontent.com/128778180/227682012-9f2c68e6-3ca6-4336-be92-11debc76b31b.mp4
Sorry for the wait, my sleep schedule's fucked.

**Comment by GSRHackZ** [comment]
Oh edgeplus servers are down rn. Contact 9295845325. I'll help you out with this.

**Comment by ChaoticCow** [comment]
I think i sent you a message.
