### ISSUE TITLE
Account issues 

### ISSUE THREAD

**Issue by 4OURTaa** [GSRHackZ/EdgyBot_Edgenuity_Bot#95]
Im being told Incorrect information. Account does not exist when my account is verified
![Opera Snapshot_2023-03-24_104608_edgybot-gsrhackz web app](https://user-images.githubusercontent.com/128830765/227575549-c64a4359-e19b-462c-ad4e-8975b79e48e1.png)

**Comment by billyonedge** [comment]
same thing is happening to me, i don’t know why it won’t sign in even when i have my info written down..

**Comment by GSRHackZ** [comment]
Both of you please contact 929-584-5325
