### ISSUE TITLE
Can't create EdgyBot account?

### ISSUE THREAD

**Issue by sussusie** [GSRHackZ/EdgyBot_Edgenuity_Bot#96]
I cannot create an EdgyBot account, I'm met with "currently fixing bugs" when I try to create an account. It's been several days now and still has not been fixed

**Comment by GSRHackZ** [comment]
Wdym by "met with currently fixing bugs"? Send a picture of this issue here

**Comment by GSRHackZ** [comment]
Have you ever tried scrolling down on the page... 🤦‍♂️
