### ISSUE TITLE
not finding answers

### ISSUE THREAD

**Issue by Ar1zzen** [GSRHackZ/EdgyBot_Edgenuity_Bot#97]
in all my classes health and career planning on any question it will open a new tab for about 1 1/2 a second then close it and tell me that there is no found answer idk if I'm reinstalling it wrong for it to keep happening but this has just come up to be an issue for just today it was working fine yesterday idk what happened if there are any answers to my problem the help will be greatly appreciated

**Comment by ITAC85v2** [comment]
This is being worked on, please be patient while we try to fix it🙏

**Comment by GSRHackZ** [comment]
Update to v3.27
