### ISSUE TITLE
edgybot account password

### ISSUE THREAD

**Issue by billyonedge** [GSRHackZ/EdgyBot_Edgenuity_Bot#98]
I have two edgyplus accounts and one of which has one class purchased and the other is 5, the class with 5 purchased doesn’t work anymore though for some reason. i used it to complete around 3 classes already through. any way i could get my account back? i have the username.

**Comment by GSRHackZ** [comment]
You are not supposed to have more than one account. Users with multiple accounts lose the previous accounts and only keep the newest ones.
