### ISSUE TITLE
Account not verified

### ISSUE THREAD

**Issue by ManiBanks** [GSRHackZ/EdgyBot_Edgenuity_Bot#99]
Hello, I just recently made a purchase and my account have not been verified yet. Thank you

**Comment by GSRHackZ** [comment]
Servers have gone down, Please wait until 6:30 am tomorrow. You account will be verified by then. 🙏

**Comment by ManiBanks** [comment]
Okay, Thank you so much

**Comment by ManiBanks** [comment]
Hello, I just check and the account is saying it’s not verified.

**Comment by GSRHackZ** [comment]
Try now, I have just verified your account 🙏

**Comment by parrotOVERLORD12** [comment]
Hello, I'd like to also have my account verified, thank you.

**Comment by GSRHackZ** [comment]
> Hello, I'd like to also have my account verified, thank you. 

Contact 9295845325
